export const pagesRoutes = [
  ["v-184f4da6","/intro.html",{"title":"About me","icon":"info","type":"page","readingTime":{"minutes":0.05,"words":16},"excerpt":"","isEncrypted":true},["/intro","/intro.md"]],
  ["v-8daa1a0e","/",{"title":"Home","icon":"home","type":"home","readingTime":{"minutes":0.16,"words":47},"excerpt":"","isEncrypted":true},["/index.html","/README.md"]],
  ["v-0e503981","/slide.html",{"title":"Slide page","icon":"slides","type":"slide","readingTime":{"minutes":3.24,"words":972},"excerpt":"","isEncrypted":true},["/slide","/slide.md"]],
  ["v-4c863446","/guide/disable.html",{"title":"Disabling layout and features","icon":"config","type":"page","readingTime":{"minutes":0.29,"words":86},"excerpt":"","category":["Guide"],"tag":["disable"],"isEncrypted":true},["/guide/disable","/guide/disable.md"]],
  ["v-bf720700","/guide/encrypt.html",{"title":"Encryption Article","icon":"lock","type":"page","readingTime":{"minutes":0.31,"words":92},"excerpt":"","category":["Guide"],"tag":["encryption"],"isEncrypted":true},["/guide/encrypt","/guide/encrypt.md"]],
  ["v-0978b044","/guide/markdown.html",{"title":"Markdown Enhance","icon":"markdown","type":"page","readingTime":{"minutes":3.14,"words":941},"excerpt":"","tag":["Markdown"],"isEncrypted":true},["/guide/markdown","/guide/markdown.md"]],
  ["v-4eaf9f84","/guide/page.html",{"title":"page config","icon":"page","type":"page","readingTime":{"minutes":0.93,"words":279},"excerpt":"","author":"Ms.Hope","date":"2020-01-01T00:00:00.000Z","localizedDate":"January 1, 2020","category":["Guide"],"tag":["Page config","Guide"],"isEncrypted":true},["/guide/page","/guide/page.md"]],
  ["v-fffb8e28","/guide/",{"title":"Guides","icon":"creative","type":"page","readingTime":{"minutes":0.08,"words":23},"excerpt":"","category":["Guide"],"isEncrypted":true},["/guide/index.html","/guide/README.md"]],
  ["v-4a3483a8","/posts/welcome.html",{"title":"Welcome","type":"article","readingTime":{"minutes":0.39,"words":118},"excerpt":"","date":"2022-07-22T00:00:00.000Z","localizedDate":"July 22, 2022","sticky":5,"isEncrypted":true},["/posts/welcome","/posts/welcome.md"]],
  ["v-3706649a","/404.html",{"title":"","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":"","isEncrypted":true},["/404"]],
  ["v-5bc93818","/category/",{"title":"Category","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":"","isEncrypted":true},["/category/index.html"]],
  ["v-744d024e","/tag/",{"title":"Tag","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":"","isEncrypted":true},["/tag/index.html"]],
  ["v-e52c881c","/article/",{"title":"Articles","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":"","isEncrypted":true},["/article/index.html"]],
  ["v-75ed4ea4","/encrypted/",{"title":"Encrypted","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":"","isEncrypted":true},["/encrypted/index.html"]],
  ["v-d804e652","/slide/",{"title":"Slides","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":"","isEncrypted":true},["/slide/index.html"]],
  ["v-154dc4c4","/star/",{"title":"Star","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":"","isEncrypted":true},["/star/index.html"]],
  ["v-01560935","/timeline/",{"title":"Timeline","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":"","isEncrypted":true},["/timeline/index.html"]],
]
